# Generated by Django 4.1.3 on 2023-02-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='column',
            new_name='max_column',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='row',
            new_name='max_row',
        ),
        migrations.RemoveField(
            model_name='location',
            name='decription',
        ),
        migrations.RemoveField(
            model_name='location',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_column',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_row',
        ),
        migrations.AddField(
            model_name='item',
            name='column',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='item',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmgmgt.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='room_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='row',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
