# Generated by Django 4.2 on 2023-04-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='column',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='max_column',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
