# Generated by Django 4.2 on 2023-04-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0002_alter_item_column_alter_location_max_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='row',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='max_row',
            field=models.IntegerField(),
        ),
    ]
