# Generated by Django 4.2 on 2023-04-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0003_alter_item_limit_alter_item_quantity_alter_item_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='max_row',
            field=models.IntegerField(default=0),
        ),
    ]
