# Generated by Django 4.2 on 2023-04-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0004_alter_location_max_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='column',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='max_column',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='max_row',
            field=models.IntegerField(),
        ),
    ]
