# Generated by Django 4.1.3 on 2023-03-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0004_machine_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmgmgt.machine'),
        ),
    ]
