# Generated by Django 4.2 on 2023-05-07 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0009_remove_user_permission_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='history',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmgmgt.item'),
        ),
        migrations.AddField(
            model_name='machine',
            name='counter_item_machine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_quantity',
            field=models.IntegerField(blank=True, default=-5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
