# Generated by Django 4.2 on 2023-05-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0010_history_creation_date_history_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
