# Generated by Django 4.2 on 2023-05-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0011_alter_machine_machine_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='counter_item_for_pn',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
