# Generated by Django 4.2 on 2023-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0015_alter_item_name_alter_item_pn_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
        migrations.RemoveField(
            model_name='history',
            name='resource',
        ),
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
