# Generated by Django 4.2 on 2023-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0016_remove_history_date_remove_history_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCost',
            fields=[
                ('month', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(default=2023)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
