# Generated by Django 4.2 on 2023-05-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0017_monthlycost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='description',
            new_name='amount',
        ),
    ]
