# Generated by Django 4.2 on 2023-06-04 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0019_alter_category_name_alter_history_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 19, 49, 48, 838491, tzinfo=datetime.timezone.utc)),
        ),
    ]
