# Generated by Django 4.2 on 2023-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0020_alter_history_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
