# Generated by Django 4.2 on 2023-06-05 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0021_alter_history_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
